export const GET_MOMENTS = "GET_MOMENTS";
export const SELECT_MOMENT = "SELECT_MOMENT";
export const DELETE_MOMENT = "DELETE_MOMENT";
export const CLEAR_SELECTION = "CLEAR_SELECTION";
export const INCREMENT_SELECTION = "INCREMENT_SELECTION";
export const DECREMENT_SELECTION = "DECREMENT_SELECTION";
