# Generated by Django 3.2 on 2021-05-02 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('entry_title', models.CharField(max_length=100)),
                ('moment_entry', models.TextField()),
                ('moment_photo', models.ImageField(blank=True, upload_to=journal.models.moment_photo_upload)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moments', to='journal.prompt')),
            ],
        ),
    ]
