# Generated by Django 3.2.1 on 2021-05-04 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_rename_moment_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='moment_entry',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='moment_photo',
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, upload_to=journal.models.entry_photo_upload),
        ),
        migrations.AlterField(
            model_name='entry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='journal.prompt'),
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=journal.models.moment_photo_upload)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
