# Generated by Django 3.2 on 2021-04-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_moment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt',
            field=models.CharField(max_length=150),
        ),
    ]
