# Generated by Django 3.2 on 2021-05-02 10:56

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_prompt_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='moment_photo',
            field=models.ImageField(blank=True, upload_to=journal.models.moment_photo_upload),
        ),
        migrations.AlterField(
            model_name='moment',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moments', to='journal.prompt'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(default='defaults/profile-placeholder.jpg', upload_to=journal.models.profile_photo_upload),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt',
            field=models.CharField(max_length=200),
        ),
    ]
